services:
  python-mcp-server:
    build:
      context: .
    container_name: python-mcp-server
    restart: unless-stopped
    init: true
    working_dir: /app
    # env_file: ./.env  # Uncomment if .env file exists
    # No ports exposed: MCP server runs over stdio, not a network port
    # No volumes: no persistent data required for this service
    # No external dependencies detected (no database, cache, or message broker required)
    # If you need to debug, consider using MCP Inspector as described in the README
